#!/bin/sh

# node already installed



 npm install express --save


#run command
#                     node server.js
# # or
#                ./node_modules/.bin/nodemon server.js
#              sudo  ./node_modules/.bin/nodemon server.js




npm install nodemon --save-dev


npm install body-parser --save
npm install mongodb --save
npm install ejs --save

# sudo service apache2 restart
